POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}}

{
  "name": "test",
  "idCard": "123321",
  "type": "1"
}

###
GET http://localhost:8000/member/passenger/query-list?page=1&size=10
Accept: application/json
token: {{token}}

###
DELETE http://localhost:8000/member/passenger/delete/1721069304222453760
Accept: application/json
token: {{token}}

###
GET http://localhost:8000/member/passenger/query-mine?
Accept: application/json
token: {{token}}