GET http://localhost:8001/member/hello
Accept: application/json

###

GET http://localhost:8000/member/hello
Accept: application/json

###

GET http://localhost:8000/member/member/count
Accept: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE2OTg3NTkyNzAsIm1vYmlsZSI6IjE1OTMxMTY2NTA2IiwiaWQiOjE3MTg1OTc5MzUxMjc3MjgxMjgsImV4cCI6MTY5ODg0NTY3MCwiaWF0IjoxNjk4NzU5MjcwfQ.6QoPmj6gogzhLtMurAHP6JKsL7jCOWu2d8I4dJo6CXE

###

POST http://localhost:8001/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=

###
POST http://localhost:8000/member/member/sendCode
Content-Type: application/x-www-form-urlencoded

mobile=15931166506

###
POST http://localhost:8000/member/member/login
Content-Type: application/x-www-form-urlencoded
# 注意这种方式为表单方式传递参数，前端的post一般为json

mobile=15931166506&code=8888
###
POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": "15931166506",
  "code": "8888"
}


